name: three_connects
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
#  file_picker: ^5.3.2
  carousel_slider: ^4.2.1
  google_fonts:
  fluttertoast: ^8.1.2
  shimmer: ^2.0.0
  beamer: ^1.5.6
  url_strategy: ^0.2.0
  number_paginator: ^0.2.3
  cached_network_image: ^3.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/social/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: oxy
      fonts:
        - asset: assets/fonts/oxygen/Oxygen-Bold.ttf
        - asset: assets/fonts/oxygen/Oxygen-Light.ttf
        - asset: assets/fonts/oxygen/Oxygen-Regular.ttf
    - family: pts
      fonts:
        - asset: assets/fonts/pt_sans/PTSans-Bold.ttf
        - asset: assets/fonts/pt_sans/PTSans-Italic.ttf
        - asset: assets/fonts/pt_sans/PTSans-Regular.ttf

