name: three_connects
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
#  file_picker: ^5.3.2
  carousel_slider: ^4.2.1
  fluttertoast: ^8.1.2
  shimmer: ^2.0.0
  beamer: ^1.5.6
  url_strategy: ^0.2.0
  number_paginator: ^0.2.3
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  otp_timer_button: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/social/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: light
      fonts:
        - asset: assets/fonts/300.ttf
    - family: pop
      fonts:
        - asset: assets/fonts/400.ttf
#        - asset: assets/fonts/500.ttf
    - family: bold
      fonts:
#        - asset: assets/fonts/600.ttf
        - asset: assets/fonts/700.ttf
#        - asset: assets/fonts/900.ttf

